// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloBD;

#nullable disable

namespace ModeloBD.Migrations
{
    [DbContext(typeof(Repositorio))]
    [Migration("20220120034216_Inicio-SRP")]
    partial class InicioSRP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaRolPagos.Entidades.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"), 1L, 1);

                    b.Property<DateTime>("Fecha_Asistencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora_Asistencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Asistencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsistenciaId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoId"), 1L, 1);

                    b.Property<int>("Departamento_Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nombre_DepartamentoDepartamentoId")
                        .HasColumnType("int");

                    b.HasKey("CargoId");

                    b.HasIndex("Nombre_DepartamentoDepartamentoId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"), 1L, 1);

                    b.Property<string>("Nombre_Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nombre_RegionRegionId")
                        .HasColumnType("int");

                    b.Property<int>("Region_Id")
                        .HasColumnType("int");

                    b.HasKey("CiudadId");

                    b.HasIndex("Nombre_RegionRegionId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContratoId"), 1L, 1);

                    b.Property<int>("Cargo_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fin_Contrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio_Contrato")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nombre_CargoCargoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sueldo_Contrato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoContrato_Id")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_ContratoTipoContratoId")
                        .HasColumnType("int");

                    b.HasKey("ContratoId");

                    b.HasIndex("Nombre_CargoCargoId");

                    b.HasIndex("Tipo_ContratoTipoContratoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"), 1L, 1);

                    b.Property<string>("Nombre_Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"), 1L, 1);

                    b.Property<string>("Apellidos_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AsistenciaEmpleadosAsistenciaId")
                        .HasColumnType("int");

                    b.Property<int>("Asistencia_Id")
                        .HasColumnType("int");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ciudad_Id")
                        .HasColumnType("int");

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<int>("Contrato_Id")
                        .HasColumnType("int");

                    b.Property<string>("Email_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Empresa_Id")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Civil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JornadaTrabajos_Id")
                        .HasColumnType("int");

                    b.Property<int>("Jornada_TrabajoJornadaTrabajoId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel_Educacion_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nombre_CiudadCiudadId")
                        .HasColumnType("int");

                    b.Property<int>("Nombre_EmpresaEmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombres_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Cuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pasaporte_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profesion_Empleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RubrosId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo_Empelado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDiscapacidad_Id")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Cuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo_DiscapacidadTipoDiscapacidadId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("AsistenciaEmpleadosAsistenciaId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("Jornada_TrabajoJornadaTrabajoId");

                    b.HasIndex("Nombre_CiudadCiudadId");

                    b.HasIndex("Nombre_EmpresaEmpresaId");

                    b.HasIndex("RubrosId");

                    b.HasIndex("Tipo_DiscapacidadTipoDiscapacidadId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"), 1L, 1);

                    b.Property<string>("Nombre_Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUC_Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representante_Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.JornadaTrabajo", b =>
                {
                    b.Property<int>("JornadaTrabajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JornadaTrabajoId"), 1L, 1);

                    b.Property<string>("Tipo_Jornada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JornadaTrabajoId");

                    b.ToTable("JornadasTrabajos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaisId"), 1L, 1);

                    b.Property<string>("Nombre_Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaisId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Permisos", b =>
                {
                    b.Property<int>("PermisosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisosId"), 1L, 1);

                    b.Property<int>("Empleado_Id")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Permiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Fin_Permiso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio_Permiso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora_Fin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hora_Inicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nombre_EmpleadoEmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPermisos_Id")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_PermisosTipoPermisosId")
                        .HasColumnType("int");

                    b.HasKey("PermisosId");

                    b.HasIndex("Nombre_EmpleadoEmpleadoId");

                    b.HasIndex("Tipo_PermisosTipoPermisosId");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"), 1L, 1);

                    b.Property<int>("Nombre_PaisPaisId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pais_Id")
                        .HasColumnType("int");

                    b.HasKey("RegionId");

                    b.HasIndex("Nombre_PaisPaisId");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.RolPagos", b =>
                {
                    b.Property<int>("RolPagosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolPagosId"), 1L, 1);

                    b.Property<string>("Descripcion_RolPagos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rubro_Id")
                        .HasColumnType("int");

                    b.HasKey("RolPagosId");

                    b.ToTable("RolPagos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Rubros", b =>
                {
                    b.Property<int>("RubrosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubrosId"), 1L, 1);

                    b.Property<int>("Dias_Gracia_Rubro")
                        .HasColumnType("int");

                    b.Property<int>("Empleado")
                        .HasColumnType("int");

                    b.Property<decimal>("Facturar_Rubro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mes_Pago_Rubro")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_Rubro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolPagosId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Rubro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RubrosId");

                    b.HasIndex("RolPagosId");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.TipoContrato", b =>
                {
                    b.Property<int>("TipoContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoContratoId"), 1L, 1);

                    b.Property<string>("Descripcion_Tipo_Contrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoContratoId");

                    b.ToTable("TiposContratos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.TipoDiscapacidad", b =>
                {
                    b.Property<int>("TipoDiscapacidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDiscapacidadId"), 1L, 1);

                    b.Property<string>("Descripcion_TipoDiscapacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDiscapacidadId");

                    b.ToTable("TiposDiscapacidades");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.TipoPermisos", b =>
                {
                    b.Property<int>("TipoPermisosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPermisosId"), 1L, 1);

                    b.Property<int>("Descripcion_Tipo_Permiso")
                        .HasColumnType("int");

                    b.HasKey("TipoPermisosId");

                    b.ToTable("TiposPermisos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Cargo", b =>
                {
                    b.HasOne("SistemaRolPagos.Entidades.Departamento", "Nombre_Departamento")
                        .WithMany()
                        .HasForeignKey("Nombre_DepartamentoDepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nombre_Departamento");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Ciudad", b =>
                {
                    b.HasOne("SistemaRolPagos.Entidades.Region", "Nombre_Region")
                        .WithMany()
                        .HasForeignKey("Nombre_RegionRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nombre_Region");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Contrato", b =>
                {
                    b.HasOne("SistemaRolPagos.Entidades.Cargo", "Nombre_Cargo")
                        .WithMany()
                        .HasForeignKey("Nombre_CargoCargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRolPagos.Entidades.TipoContrato", "Tipo_Contrato")
                        .WithMany()
                        .HasForeignKey("Tipo_ContratoTipoContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nombre_Cargo");

                    b.Navigation("Tipo_Contrato");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Empleado", b =>
                {
                    b.HasOne("SistemaRolPagos.Entidades.Asistencia", "AsistenciaEmpleados")
                        .WithMany("Lista_Empleados")
                        .HasForeignKey("AsistenciaEmpleadosAsistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRolPagos.Entidades.Contrato", "contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRolPagos.Entidades.JornadaTrabajo", "Jornada_Trabajo")
                        .WithMany()
                        .HasForeignKey("Jornada_TrabajoJornadaTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRolPagos.Entidades.Ciudad", "Nombre_Ciudad")
                        .WithMany()
                        .HasForeignKey("Nombre_CiudadCiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRolPagos.Entidades.Empresa", "Nombre_Empresa")
                        .WithMany()
                        .HasForeignKey("Nombre_EmpresaEmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRolPagos.Entidades.Rubros", null)
                        .WithMany("Lista_Empleado")
                        .HasForeignKey("RubrosId");

                    b.HasOne("SistemaRolPagos.Entidades.TipoDiscapacidad", "Tipo_Discapacidad")
                        .WithMany()
                        .HasForeignKey("Tipo_DiscapacidadTipoDiscapacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsistenciaEmpleados");

                    b.Navigation("Jornada_Trabajo");

                    b.Navigation("Nombre_Ciudad");

                    b.Navigation("Nombre_Empresa");

                    b.Navigation("Tipo_Discapacidad");

                    b.Navigation("contrato");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Permisos", b =>
                {
                    b.HasOne("SistemaRolPagos.Entidades.Empleado", "Nombre_Empleado")
                        .WithMany()
                        .HasForeignKey("Nombre_EmpleadoEmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRolPagos.Entidades.TipoPermisos", "Tipo_Permisos")
                        .WithMany()
                        .HasForeignKey("Tipo_PermisosTipoPermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nombre_Empleado");

                    b.Navigation("Tipo_Permisos");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Region", b =>
                {
                    b.HasOne("SistemaRolPagos.Entidades.Pais", "Nombre_Pais")
                        .WithMany()
                        .HasForeignKey("Nombre_PaisPaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nombre_Pais");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Rubros", b =>
                {
                    b.HasOne("SistemaRolPagos.Entidades.RolPagos", null)
                        .WithMany("Lista_Rubros")
                        .HasForeignKey("RolPagosId");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Asistencia", b =>
                {
                    b.Navigation("Lista_Empleados");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.RolPagos", b =>
                {
                    b.Navigation("Lista_Rubros");
                });

            modelBuilder.Entity("SistemaRolPagos.Entidades.Rubros", b =>
                {
                    b.Navigation("Lista_Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
